In [1]:
import numpy as np

# Define the dataset
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([2, 4, 6, 8, 10])
y = np.array([5, 8, 11, 14, 17])

# Define the learning rate and number of epochs
lr = 0.01
epochs = 1000

# Initialize the weights and bias
w = np.array([0.0, 0.0])
b = 0.0

# Define the total number of samples
n = float(len(x1))

# Perform gradient descent
for i in range(epochs):
    # Calculate the predicted y values
    y_pred = np.dot(w, np.array([x1, x2])) + b
    
    # Calculate the derivatives of the weights and bias
    d_w = (1/n) * np.dot(np.array([x1, x2]), (y_pred - y))
    d_b = (1/n) * sum(y_pred - y)
    
    # Update the weights and bias
    w = w - lr * d_w
    b = b - lr * d_b
    
    # Calculate the total loss function
    loss = (1/(2*n)) * sum((y_pred - y)**2)
    
    # Print the loss every 100 epochs
    if i % 100 == 0:
        print("Epoch {}: Loss = {}".format(i, loss))
        
# Print the final weights and bias
print("Final weights: w1 = {}, w2 = {}, b = {}".format(w[0], w[1], b))

Epoch 0: Loss = 69.5
Epoch 100: Loss = 0.20779771307930472
Epoch 200: Loss = 0.14517715202654205
Epoch 300: Loss = 0.10142751408671152
Epoch 400: Loss = 0.07086198117407136
Epoch 500: Loss = 0.04950747754323927
Epoch 600: Loss = 0.034588227595182514
Epoch 700: Loss = 0.024164945328335154
Epoch 800: Loss = 0.01688275529916876
Epoch 900: Loss = 0.011795078474992296
Final weights: w1 = 0.6164755729372513, w2 = 1.2329511458745026, b = 1.698931665649957

In [3]:
import pandas as pd
import uuid
import random

In [14]:
 df = pd.DataFrame(np.random.randint(0,1000,size=(50, 2)), columns=list('AB'))

In [15]:
df

      A    B
0   654  105
1   760  566
2   898  515
3   351  834
4    32  443
5    34  505
6   807  956
7   918  131
8   594  446
9   663  548
10  819  273
11  694  297
12   53  756
13  959  837
14  264  746
15   23  423
16  752  951
17  292  759
18   42  277
19   91  491
20  905  784
21   76  898
22  304  740
23  545  607
24  278   15
25  533  246
26    0  123
27  876  463
28  624  637
29   65  155
30  720  779
31  663  910
32  167  836
33  206  293
34  674  118
35  313  183
36  199  547
37  723  414
38  508  814
39  461  936
40  349  650
41  403  980
42  255   43
43  852   20
44  650  137
45  444  742
46  254  976
47  917  341
48  560  651
49  446  288

In [16]:
df["Y"] = df['A'] + df['B']

In [17]:
df

      A    B     Y
0   654  105   759
1   760  566  1326
2   898  515  1413
3   351  834  1185
4    32  443   475
5    34  505   539
6   807  956  1763
7   918  131  1049
8   594  446  1040
9   663  548  1211
10  819  273  1092
11  694  297   991
12   53  756   809
13  959  837  1796
14  264  746  1010
15   23  423   446
16  752  951  1703
17  292  759  1051
18   42  277   319
19   91  491   582
20  905  784  1689
21   76  898   974
22  304  740  1044
23  545  607  1152
24  278   15   293
25  533  246   779
26    0  123   123
27  876  463  1339
28  624  637  1261
29   65  155   220
30  720  779  1499
31  663  910  1573
32  167  836  1003
33  206  293   499
34  674  118   792
35  313  183   496
36  199  547   746
37  723  414  1137
38  508  814  1322
39  461  936  1397
40  349  650   999
41  403  980  1383
42  255   43   298
43  852   20   872
44  650  137   787
45  444  742  1186
46  254  976  1230
47  917  341  1258
48  560  651  1211
49  446  288   734

In [19]:
df_final=df.rename(columns={"A": "X1", "B": "X2"})

In [22]:
df_final

     X1   X2     Y
0   654  105   759
1   760  566  1326
2   898  515  1413
3   351  834  1185
4    32  443   475
5    34  505   539
6   807  956  1763
7   918  131  1049
8   594  446  1040
9   663  548  1211
10  819  273  1092
11  694  297   991
12   53  756   809
13  959  837  1796
14  264  746  1010
15   23  423   446
16  752  951  1703
17  292  759  1051
18   42  277   319
19   91  491   582
20  905  784  1689
21   76  898   974
22  304  740  1044
23  545  607  1152
24  278   15   293
25  533  246   779
26    0  123   123
27  876  463  1339
28  624  637  1261
29   65  155   220
30  720  779  1499
31  663  910  1573
32  167  836  1003
33  206  293   499
34  674  118   792
35  313  183   496
36  199  547   746
37  723  414  1137
38  508  814  1322
39  461  936  1397
40  349  650   999
41  403  980  1383
42  255   43   298
43  852   20   872
44  650  137   787
45  444  742  1186
46  254  976  1230
47  917  341  1258
48  560  651  1211
49  446  288   734

In [ ]:
df1['randNumCol'] = np.random.randint(1, 6, df1.shape[0])

In [39]:
from sklearn import preprocessing
import pandas as pd
d = preprocessing.normalize(df_final)
df_scaled = pd.DataFrame(d, columns=['X1','X2','Y'])

In [42]:
df_scaled

          X1        X2         Y
0   0.649206  0.104230  0.753437
1   0.466316  0.347283  0.813599
2   0.512666  0.294012  0.806678
3   0.235418  0.559369  0.794786
4   0.049208  0.681218  0.730425
5   0.045984  0.682993  0.728976
6   0.373301  0.442225  0.815526
7   0.655666  0.093565  0.749231
8   0.464779  0.348976  0.813755
9   0.446346  0.368926  0.815272
10  0.588348  0.196116  0.784465
11  0.557088  0.238408  0.795496
12  0.047811  0.681988  0.729799
13  0.435645  0.380224  0.815869
14  0.205754  0.581410  0.787164
15  0.037391  0.687669  0.725060
16  0.359726  0.454919  0.814645
17  0.219732  0.571154  0.790886
18  0.098925  0.652435  0.751360
19  0.118665  0.640267  0.758931
20  0.437121  0.378678  0.815799
21  0.057273  0.676728  0.734002
22  0.231130  0.562619  0.793750
23  0.386090  0.430012  0.816103
24  0.687820  0.037113  0.724932
25  0.546431  0.252199  0.798630
26  0.000000  0.707107  0.707107
27  0.525895  0.277956  0.803850
28  0.404032  0.412450  0.816482
29  0.234778  0.559855  0.794633
30  0.392079  0.424207  0.816286
31  0.342738  0.470424  0.813162
32  0.126865  0.635086  0.761952
33  0.335376  0.477015  0.812391
34  0.643963  0.112741  0.756704
35  0.509449  0.297857  0.807306
36  0.210311  0.578092  0.788403
37  0.512922  0.293706  0.806628
38  0.310987  0.498314  0.809302
39  0.264392  0.536813  0.801205
40  0.281022  0.523394  0.804416
41  0.231308  0.562485  0.793793
42  0.646289  0.108982  0.755271
43  0.698763  0.016403  0.715166
44  0.631146  0.133026  0.764172
45  0.302503  0.505535  0.808038
46  0.159689  0.613607  0.773296
47  0.575407  0.213974  0.789381
48  0.377216  0.438513  0.815729
49  0.492340  0.317923  0.810263

In [49]:
df_scaled['Y1'] = np.random.randint(0, 2, df_scaled.shape[0])

In [50]:
df_scaled

          X1        X2         Y  Y1
0   0.649206  0.104230  0.753437   0
1   0.466316  0.347283  0.813599   1
2   0.512666  0.294012  0.806678   0
3   0.235418  0.559369  0.794786   0
4   0.049208  0.681218  0.730425   1
5   0.045984  0.682993  0.728976   1
6   0.373301  0.442225  0.815526   0
7   0.655666  0.093565  0.749231   1
8   0.464779  0.348976  0.813755   0
9   0.446346  0.368926  0.815272   1
10  0.588348  0.196116  0.784465   0
11  0.557088  0.238408  0.795496   1
12  0.047811  0.681988  0.729799   1
13  0.435645  0.380224  0.815869   0
14  0.205754  0.581410  0.787164   0
15  0.037391  0.687669  0.725060   0
16  0.359726  0.454919  0.814645   0
17  0.219732  0.571154  0.790886   0
18  0.098925  0.652435  0.751360   0
19  0.118665  0.640267  0.758931   0
20  0.437121  0.378678  0.815799   1
21  0.057273  0.676728  0.734002   1
22  0.231130  0.562619  0.793750   0
23  0.386090  0.430012  0.816103   1
24  0.687820  0.037113  0.724932   1
25  0.546431  0.252199  0.798630   1
26  0.000000  0.707107  0.707107   1
27  0.525895  0.277956  0.803850   0
28  0.404032  0.412450  0.816482   1
29  0.234778  0.559855  0.794633   1
30  0.392079  0.424207  0.816286   1
31  0.342738  0.470424  0.813162   0
32  0.126865  0.635086  0.761952   0
33  0.335376  0.477015  0.812391   1
34  0.643963  0.112741  0.756704   0
35  0.509449  0.297857  0.807306   0
36  0.210311  0.578092  0.788403   1
37  0.512922  0.293706  0.806628   0
38  0.310987  0.498314  0.809302   0
39  0.264392  0.536813  0.801205   1
40  0.281022  0.523394  0.804416   0
41  0.231308  0.562485  0.793793   1
42  0.646289  0.108982  0.755271   0
43  0.698763  0.016403  0.715166   0
44  0.631146  0.133026  0.764172   0
45  0.302503  0.505535  0.808038   1
46  0.159689  0.613607  0.773296   0
47  0.575407  0.213974  0.789381   1
48  0.377216  0.438513  0.815729   0
49  0.492340  0.317923  0.810263   0

In [46]:
d1 = preprocessing.normalize(df_scaled)
df_scaled_new = pd.DataFrame(d1, columns=['X1','X2','Y','Y1'])

In [43]:
import numpy as np

# Define the dataset
x1 = np.array(df_scaled['X1'])
x2 = np.array(df_scaled['X2'])
y = np.array(df_scaled['Y'])
# Define the learning rate and number of epochs
learning_rate = 0.0001
epochs = 1000

# Initialize the weight vector and bias
w1 = 0
w2 = 0
b = 0

# Define the number of samples
n = len(x1)

# Define the total loss function
def total_loss(y_hat, y):
    return np.sum((y_hat - y) ** 2) / (2 * n)

# Define the partial derivative of the loss function with respect to the weight vector and bias
def partial_derivative(y_hat, y, x):
    return np.sum((y_hat - y) * x) / n

# Train the model using gradient descent
for i in range(epochs):
    # Compute the predictions
    y_hat = w1 * x1 + w2 * x2 + b
    
    # Compute the gradients
    dw1 = partial_derivative(y_hat, y, x1)
    dw2 = partial_derivative(y_hat, y, x2)
    db = np.sum(y_hat - y) / n
    
    # Update the weight vector and bias
    w1 -= learning_rate * dw1
    w2 -= learning_rate * dw2
    b -= learning_rate * db
    
    # Compute the total loss
    loss = total_loss(y_hat, y)
    
    # Print the loss every 100 epochs
    if i % 100 == 0:
        print(f"Epoch {i}: Loss = {loss}")

# Print the final weight vector and bias
print(f"Weight Vector: [{w1}, {w2}]")
print(f"Bias: {b}")

Epoch 0: Loss = 0.30760244621173416
Epoch 100: Loss = 0.29966287093370203
Epoch 200: Loss = 0.291928465239003
Epoch 300: Loss = 0.2843939272036248
Epoch 400: Loss = 0.2770540919141951
Epoch 500: Loss = 0.2699039279273963
Epoch 600: Loss = 0.2629385338208736
Epoch 700: Loss = 0.25615313483327545
Epoch 800: Loss = 0.24954307959111902
Epoch 900: Loss = 0.24310383692024043
Weight Vector: [0.026788905605690035, 0.030883276095224836]
Bias: 0.07345812793903257

In [52]:
import numpy as np

# Define the dataset
x1 = np.array(df_scaled['X1'])
x2 = np.array(df_scaled['X2'])
y = np.array(df_scaled['Y1'])
# Normalize the data
x1 = (x1 - np.mean(x1)) / np.std(x1)
x2 = (x2 - np.mean(x2)) / np.std(x2)

# Define the learning rate and number of epochs
learning_rate = 0.0001
epochs = 1000

# Initialize the weight vector and bias
w1 = 0
w2 = 0
b = 0

# Define the sigmoid activation function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Define the number of samples
n = len(x1)

# Define the total loss function
def total_loss(y_hat, y):
    return -np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)) / n

# Define the partial derivative of the loss function with respect to the weight vector and bias
def partial_derivative(y_hat, y, x):
    return np.sum((y_hat - y) * x) / n

# Train the model using gradient descent
for i in range(epochs):
    # Compute the linear equation and the predictions
    z = w1 * x1 + w2 * x2 + b
    y_hat = sigmoid(z)
    
    # Compute the gradients
    dw1 = partial_derivative(y_hat, y, x1)
    dw2 = partial_derivative(y_hat, y, x2)
    db = np.sum(y_hat - y) / n
    
    # Update the weight vector and bias
    w1 -= learning_rate * dw1
    w2 -= learning_rate * dw2
    b -= learning_rate * db
    
    # Compute the total loss
    loss = total_loss(y_hat, y)
    
    # Print the loss every 100 epochs
    if i % 100 == 0:
        print(f"Epoch {i}: Loss = {loss}")
        
# Define a function to predict the label based on the trained model
def predict(x1, x2):
    z = w1 * x1 + w2 * x2 + b
    y_hat = sigmoid(z)
    return np.round(y_hat).astype(int)

# Test the model
print("Predictions:", predict(x1, x2))

Epoch 0: Loss = 0.6931471805599453
Epoch 100: Loss = 0.6930331430339297
Epoch 200: Loss = 0.6929200557230694
Epoch 300: Loss = 0.6928079101101777
Epoch 400: Loss = 0.6926966977558102
Epoch 500: Loss = 0.6925864102975983
Epoch 600: Loss = 0.6924770394495873
Epoch 700: Loss = 0.6923685770015808
Epoch 800: Loss = 0.6922610148184863
Epoch 900: Loss = 0.6921543448396669
Predictions: [0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0 0 0 1
 0 0 1 0 1 0 0 0 0 1 0 0 0]